### ISSUE TITLE
Add subject segmentation  package  

### ISSUE THREAD

**Issue by alihassan143** [Knightro63/apple_vision#8]
add package so user can select subject and perform different operation using apple vision subject lift api

**Comment by Knightro63** [comment]
Hi @alihassan143,

I have added a version of apple vision lift subject. 

https://github.com/Knightro63/apple_vision/tree/main/packages/apple_vision_lift_subjects

https://pub.dev/packages/apple_vision_lift_subjects

Hope this helps.

**Comment by alihassan143** [comment]
@Knightro63  but its not supported for ios

**Comment by Knightro63** [comment]
Hi @alihassan143,

I will need a newer iOS device in order to test this. It might take a couple of more weeks to get it working for iOS.

**Comment by alihassan143** [comment]
you can test on simulator

**Comment by Knightro63** [comment]
Hi @alihassan143,

This package requires an actual device for testing. I have finished apple_vision_lift_subjects api. 

The locations of the packages are listed below.
https://github.com/Knightro63/apple_vision/tree/main/packages/apple_vision_lift_subjects

https://pub.dev/packages/apple_vision_lift_subjects

Hope this helps.
